### ISSUE TITLE
Разобраться с решением прямой задачи кинематики

### ISSUE THREAD

**Issue by Robotics010** [Robotics010/volcaano-arm#2]
Перед тем, как управление по звеньям будет апробировано физически на роботе, необходимо проработать их "на бумаге". В нашем случае нужно

- [x] расписать кинематическую модель в DH системе
- [x] задать начальные положения для каждого из звеньев
- [x] приложить скрипт на языке Python, где решается прямая задача кинематики
- [x] сравнить решение прямой задачи с известным решением из учебника
- [x] посчитать начальное и демо положение для робота на основе скрипта

**Comment by Robotics010** [comment]
@vesebr написал [программы для решения прямой задачи для 2d варианта и в пространстве](https://github.com/Robotics010/volcaano-arm/blob/master/host/tools/kinematic/Pryamaya_3D.py).

**Comment by Robotics010** [comment]
@vesebr прислал начальное положение манипулятора
решение соответствует решению прямой задачи из книги "Управление роботами" - Ющенко, гл. 2.1
![ZBv8wLOv6Cg](https://user-images.githubusercontent.com/16175093/99877621-91136b80-2c10-11eb-8aae-aa86a6f6da17.jpg)

**Comment by Robotics010** [comment]
Внешний вид робота
![9jtZuTgeLJU](https://user-images.githubusercontent.com/16175093/99877661-b902cf00-2c10-11eb-92b6-dd0b53821be0.jpg)

**Comment by Robotics010** [comment]
Проверил работу скрипта, выглядит верно, а на каком примере численном примере ты его проверял? В главе 2.1 нет численных примеров.

Прошу при следующих изменениях заодно внести следующие изменения:
- [x] При запросе пользователя о вводе величины, указывать ожидаемые единицы измерения
- [x] Перевод из градусов в радианы выполнять при помощи встроенной в numpy функции, а не самостоятельно
- [x] Весь русскоязычный вывод на экран перевести на английский

**Comment by Robotics010** [comment]
- [x] Можешь нарисовать исходное положение робота графически? при q1=180deg, q2 = 90deg, q3 = q4 = 0

Нарисовать можно как вручную на листке бумаги, так и при помощи компьютера.

**Comment by vesebr** [comment]
Исправил замечания. В программе теперь все на английском языке. Схему робота прилагаю
![Схема робота](https://user-images.githubusercontent.com/10115053/99901944-b3ba8880-2cd3-11eb-98fa-a6008a1c359f.jpg)
[Добавил исправленную версию программы](https://github.com/Robotics010/volcaano-arm/blob/master/host/tools/kinematic/Pryamaya_new.py)
Решение составлено на основе примера 2.1 из главы 2.1 книги "Управление роботами" Ющенко
