### ISSUE TITLE
Проверить библиотеку с двигателем М1, М2... М5 по отдельности

### ISSUE THREAD

**Issue by Robotics010** [Robotics010/volcaano-arm#4]
Необходимо восстановить работу робота после прошлой команды. Когда будет обновлена библиотека #1, нужно будет проверить работу каждого из двигателя М1, М2, М3, М4 и М5 по отдельности и желательно на столе, отдельно от конструкции робота, т.к. неправильная работа двигателей могут повредить распечатанную конструкцию робота.

- [x] Проверить работу М1
- [x] Проверить работу М2
- [x] Проверить работу М3
- [x] Проверить работу М4
- [x] Проверить работу М5

**Comment by Robotics010** [comment]
@DekartVan 3 ноября:

В общем, собрал схему. Начал загружать код. Вроде как всё выполняется, но пока ничего сказать не могу, обнаружились другие проблемы.
1. Ардуинка всё также греется... Следовательно, дальше при той же схеме работать нельзя, погорит и вторая.
2. В поисках проблемы пересмотрел весь драйвер и на нём есть проблема - дорожки остоеденены и некоторые из входов просто не работали. Нужно будет превести в норму драйвер и найти из-за чего греется ардуинка.

**Comment by DekartVan** [comment]
Написали новую библиотеку для управления двигателями, а также проверили их по отдельности и все вместе. Все моторы находятся в рабочем состоянии и справляются с работой даже под нагрузкой.
