### ISSUE TITLE
Проверить эл схему подключения усилителя и сам усилитель

### ISSUE THREAD

**Issue by Robotics010** [Robotics010/volcaano-arm#5]
При проверке библиотеки #4 всплыли проблемы с arduino+усилитель из-за чего сгорел предыдущий контроллер arduino.
Для решения нужно:

- [x] проверить электрическую схему на корректность
![BlxBXGavpZU](https://user-images.githubusercontent.com/16175093/99878359-dbe3b200-2c15-11eb-94e3-e8129766fe58.jpg)

- [x] Проверить работоспособность самого усилителя
![Jl011CNnW1g](https://user-images.githubusercontent.com/16175093/99878335-a6d75f80-2c15-11eb-9eda-f428c0d9f281.jpg)

**Comment by Robotics010** [comment]
Подключение сейчас выглядит вот так:
![PmZ8Gze35As](https://user-images.githubusercontent.com/16175093/99878391-14838b80-2c16-11eb-88e9-142810b72fc0.jpg)


Фото драйверов в близи до монтажа:
![D2_2](https://user-images.githubusercontent.com/16175093/99878397-1e0cf380-2c16-11eb-9235-9aa759609f7c.jpg)

![D2_3](https://user-images.githubusercontent.com/16175093/99878399-206f4d80-2c16-11eb-89ea-57ae947d28f9.jpg)

**Comment by DekartVan** [comment]
Установил проблему из-за которой сгорела предыдущая Arduino Mega. Дело в том, что при подключении в соответствии со старой схемой (оставшейся ещё с прежних времён и в будущем переделанной мной) усилитель D_2 питался от блока питания на 12V, а arduino отдельно от USB либо другого источника и ещё мы подключали 5V с усилителя с 5V с arduino из-за чего на ней возникало серьёзное напряжение. Переделываю схему подключения.

**Comment by DekartVan** [comment]
На данный момент у нас 5 рабочих усилителей. Несколько раз перепроверили настоящую схему подключения. Причину, по которой сгорела старая Arduino сказать трудно. Есть предположение - возможно, что был скачок напряжения из-за неправильной эксплуатации. Сейчас пересобрали схему и проверили работу мотора M1_1, arduino работает в штатном режиме и не греется. Сейчас проверяем все моторы по отдельности.

**Comment by DekartVan** [comment]
Проблема с подключением была устранена. Причина, по которая сгорали компоненты также удалось обнаружить и решить установкой нескольких диодов в схему (проблема была в пинах питания логической части драйверов +5v и GND, так как при работе драйверов под нагрузкой на пинах возникал обратный ток, который поступал непосредственно на микроконтроллер и выводил его из строя). Теперь всё работает в штатном режиме без перегревов и помех на контактах (также на выводы двигателей M+ и M- были установлены кремневые конденсаторы, так как до этого наблюдались помехи из за наведённых сигналов). Схема была полностью собранно и множество раз протестирована.
